name: Yakka Build

on:
  push:
    branches: [master, "nik/0.8.0"]
  pull_request:
    branches: [master]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./yakka-linux link! yakka_cli gcc
      - run: mv ${{github.workspace}}/output/yakka_cli-gcc/yakka_cli-gcc ${{github.workspace}}/output/yakka_cli-gcc/yakka-linux
      - uses: actions/upload-artifact@v4
        with:
          name: Linux executable
          path: ${{github.workspace}}/output/yakka_cli-gcc/yakka-linux
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Linux build log
          path: ${{github.workspace}}/yakka.log
  build_windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - run: "dir env:"
      - run: 'dir "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/"'
      - run: 'dir "C:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/"'
      - run: ./yakka-windows link! yakka_cli msvc
      - run: mv ${{github.workspace}}/output/yakka_cli-msvc/yakka_cli-msvc.exe ${{github.workspace}}/output/yakka_cli-msvc/yakka-windows.exe
      - uses: actions/upload-artifact@v4
        with:
          name: Windows executable
          path: ${{github.workspace}}/output/yakka_cli-msvc/yakka-windows.exe
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Windows build log
          path: ${{github.workspace}}/yakka.log
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./yakka-macos link! yakka_cli xcode
      - run: mv ${{github.workspace}}/output/yakka_cli-xcode/yakka_cli-xcode ${{github.workspace}}/output/yakka_cli-xcode/yakka-macos
      - uses: actions/upload-artifact@v4
        with:
          name: MacOS executable
          path: ${{github.workspace}}/output/yakka_cli-xcode/yakka-macos
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: MacOS build log
          path: ${{github.workspace}}/yakka.log
